spring.application.name=demo
# ===============================
# Server configuration
# ===============================
server.port=8443
server.address=0.0.0.0
server.ssl.key-store=classpath:keys/keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

# Optional: Require HTTPS for all requests
server.ssl.enabled=true
# ===============================
# PostgreSQL Database configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/application
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=data

# ===============================
# Liquibase configuration
# ===============================
spring.liquibase.change-log=classpath:db/changelog/changelog.yaml
spring.liquibase.enabled=true
spring.liquibase.liquibase-schema=data

# ===============================
# JWT configuration
# ===============================
jwt.issuer=https://api.fittracker.com
jwt.audience=fit-tracker-mobile
jwt.access-token-expiration=15m
jwt.refresh-token-expiration=30d

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.private-key=classpath:keys/private.pem
jwt.public-key=classpath:keys/public.pem

#myDiplomApps
#spring.mail.host=smtp.yandex.ru
#spring.mail.port=587
#spring.mail.username=no-reply@yandex.ru
##spring.mail.password=gxtkhuezrqdcwjxg
#spring.mail.password=bpxhhnldgrhrbtho
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.debug=true

spring.mail.host=smtp.yandex.ru
spring.mail.port=587
spring.mail.username=no-reply@yandex.ru
spring.mail.password=gxtkhuezrqdcwjxg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.debug=true


app.avatar.storage.path=./src/main/resources/templates/avatars
app.avatar.base-url=https://10.0.2.2:8443/api/files

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

